# Generated by Django 5.2.6 on 2025-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mat', models.FloatField(blank=True, null=True)),
                ('vmc', models.FloatField(blank=True, null=True)),
                ('cnc', models.FloatField(blank=True, null=True)),
                ('hand', models.FloatField(blank=True, null=True)),
                ('laser', models.FloatField(blank=True, null=True)),
                ('bend', models.FloatField(blank=True, null=True)),
                ('weld', models.FloatField(blank=True, null=True)),
                ('ext', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('unit', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('project_name', 'part_no')},
            },
        ),
    ]
