# Generated by Django 5.2.6 on 2025-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='quotation_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
