# Generated by Django 5.2.6 on 2025-10-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_projectdata_quotation_name_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
