# Generated by Django 5.2.6 on 2025-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_projectdata_grand_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('quotationname', models.CharField(blank=True, max_length=100, null=True)),
                ('grandTotal', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
