# Generated by Django 5.2.6 on 2025-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_dashboarddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='quotationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
