# Generated by Django 5.2.6 on 2025-10-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0006_dashboarddata_quotationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='quotationDate',
        ),
    ]
