# Generated by Django 5.2.6 on 2025-10-29 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0007_remove_dashboarddata_quotationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
