# Generated by Django 5.2.6 on 2025-10-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0008_dashboarddata_last_modified_projectdata_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='updated_at',
        ),
    ]
