# Generated by Django 5.2.6 on 2025-10-29 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0009_remove_dashboarddata_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='latest_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
