# Generated by Django 5.2.6 on 2025-10-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0010_dashboarddata_latest_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboarddata',
            old_name='latest_modified',
            new_name='last_date',
        ),
    ]
