# Generated by Django 5.2.6 on 2025-10-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0011_rename_latest_modified_dashboarddata_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdata',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='quotation_name',
        ),
    ]
