# Generated by Django 5.2.6 on 2025-11-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0012_remove_projectdata_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='last_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
