# Generated by Django 5.2.6 on 2025-11-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0013_alter_dashboarddata_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='last_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
