# Generated by Django 5.2.6 on 2025-11-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0015_numberentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='grandTotal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='quotationname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
