# Generated by Django 5.2.6 on 2025-11-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0016_alter_dashboarddata_grandtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='grandTotal',
            field=models.FloatField(default=0),
        ),
    ]
