# Generated by Django 5.2.6 on 2025-11-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0017_alter_dashboarddata_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='grandTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='quotationname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
