# Generated by Django 5.2.6 on 2025-11-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0018_alter_dashboarddata_grandtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='projectStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
