# Generated by Django 5.2.6 on 2025-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0019_dashboarddata_projectstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(max_length=125)),
            ],
        ),
    ]
