# Generated by Django 5.2.6 on 2025-12-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0020_ponumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('quotationname', models.CharField(blank=True, max_length=125, null=True)),
                ('order_serial', models.CharField(max_length=125, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=125, null=True)),
                ('po_status', models.CharField(blank=True, max_length=125, null=True)),
                ('dc_number', models.CharField(blank=True, max_length=125, null=True)),
                ('dispatch_date', models.CharField(blank=True, max_length=10, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=125, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=125, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=125, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=125, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
