# Generated by Django 5.2.6 on 2025-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0021_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('projectName', models.CharField(blank=True, max_length=125, null=True)),
                ('job_status', models.CharField(blank=True, max_length=125, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
