# Generated by Django 5.2.6 on 2025-12-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0022_jobstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstatus',
            old_name='remarks',
            new_name='remark',
        ),
    ]
