# Generated by Django 5.2.6 on 2025-12-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0023_rename_remarks_jobstatus_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobStatus',
        ),
    ]
