# Generated by Django 5.2.6 on 2025-12-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0024_delete_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='part_status',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
