# Generated by Django 5.2.6 on 2025-12-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0025_projectdata_part_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='part_remark',
            field=models.FloatField(blank=True, max_length=350, null=True),
        ),
    ]
