# Generated by Django 5.2.6 on 2025-12-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0026_projectdata_part_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='part_remark',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='part_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
