# Generated by Django 5.2.6 on 2025-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0027_alter_projectdata_part_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='part_remark',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
