# Generated by Django 5.2.6 on 2026-03-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0029_uploadjob_delete_numberentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='ext_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
