# Generated by Django 5.2.6 on 2026-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0030_dashboarddata_ext_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='po_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
