# Generated by Django 5.2.6 on 2026-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0031_projectdata_po_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='po_contact',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
