# Generated by Django 5.2.6 on 2026-03-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0032_orderstatus_po_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='PoNumber',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='ext_info',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='projectStatus',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='part_remark',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='part_status',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='po_reference',
        ),
        migrations.DeleteModel(
            name='UploadJob',
        ),
    ]
