# Generated by Django 5.2.6 on 2026-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0033_delete_orderstatus_delete_ponumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('quotationname', models.CharField(blank=True, max_length=125, null=True)),
                ('order_serial', models.CharField(max_length=125, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=125, null=True)),
                ('po_status', models.CharField(blank=True, max_length=125, null=True)),
                ('dc_number', models.CharField(blank=True, max_length=125, null=True)),
                ('dispatch_date', models.CharField(blank=True, max_length=10, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=125, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=125, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=125, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=125, null=True)),
                ('po_contact', models.CharField(blank=True, max_length=125, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='ext_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='projectStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='part_remark',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='part_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='po_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
